---
- name: ensure required nginx packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - nginx

- name: ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
