---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - git
    - mongodb-server
    - mongodb-dev
    - redis-server
    - texlive
    - nodejs
    - npm

- name: ensure that node links to nodejs
  file:
    path: /usr/local/bin/node
    src: /usr/bin/nodejs
    state: link

- name: ensure that grunt is installed using npm
  npm:
    name: grunt-cli
    state: latest
    global: yes

- name: get latexmk from source
  get_url:
    url: http://mirrors.ctan.org/support/latexmk/latexmk.pl
    dest: /usr/local/bin/latexmk
    force: yes

- name: ensure latexmk has proper permissions
  file:
    path: /usr/local/bin/latexmk
    owner: root
    group: root
    mode: 0755
    state: file
- name: ensure that sharelatex group exists
  group:
    name: sharelatex
    state: present

- name: ensure that sharelatex user exits
  user:
    name: sharelatex
    group: sharelatex
    home: /srv/sharelatex
    createhome: no
    shell: /bin/bash
    comment: sharelatexLab User
    state: present

- name: check sharelatex out of git repository
  git:
    repo: https://github.com/sharelatex/sharelatex.git
    dest: /srv/sharelatex
    update: yes
  notify:
    - restart sharelatex

- name: ensure /srv/sharelatex ownership is correct
  file:
    path: /srv/sharelatex
    owner: sharelatex
    group: sharelatex
    recurse: yes

- name: install npm packages
  sudo_user: sharelatex
  shell: npm install && touch .npm_install
         executable=/bin/bash
         chdir=/srv/sharelatex
         creates=/srv/sharelatex/.npm_install
  notify:
    - restart sharelatex

- name: run grunt install
  sudo_user: sharelatex
  shell: grunt install && touch .grunt_install
         executable=/bin/bash
         chdir=/srv/sharelatex
         creates=/srv/sharelatex/.grunt_install
  notify:
    - restart sharelatex

- name: ensure sharelatex init script is installed and up to date
  template:
    src: etc/init/sharelatex.conf
    dest: /etc/init/sharelatex.conf
    owner: root
    group: root
    mode: 0644

- name: ensure sharelatex service is started and enabled
  service:
    name: sharelatex
    state: started
    enabled: yes

- name: update nginx sharelatex configuration from template
  template:
    src: etc/nginx/sites-available/sharelatex
    dest: /etc/nginx/sites-available/sharelatex
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: enable sharelatex nginx configuration
  file:
    src: ../sites-available/sharelatex
    path: /etc/nginx/sites-enabled/sharelatex
    state: link
  notify:
    - restart nginx
